websms:
  image: node:8.10
  build: /home/ubuntu/src/nodejssms
  privileged: false
  restart: always
  ports:
  - 80:3000
  volumes:  
    - /home/ubuntu/bin/nodejssms:/home/ubuntu/src/nodejssms
  environment:
  - NODE_ENV=product
  - PORT=3000